#! /bin/sh
### BEGIN INIT INFO
# Provides:             stalker-agent
# Required-Start:       $syslog $remote_fs
# Required-Stop:        $syslog $remote_fs
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    stalker-agent for stalker monitoring system
# Description:          stalker-agent for stalker monitoring system
### END INIT INFO

USER=nobody
GROUP=adm #so checks can still access logs
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
CONF=/etc/stalker/stalker-agent.conf
NAME=stalker-agent
DESC=stalker-agent
RUNDIR=/var/run/stalker
PIDFILE=$RUNDIR/stalker-agent.pid
DAEMON=/usr/bin/stalker-agent
DAEMON_ARGS_START="--pid=$PIDFILE --conf=$CONF start"
DAEMON_ARGS_STOP="--pid=$PIDFILE --conf=$CONF stop"

# Carry out specific functions when asked to by the system
case "$1" in
    start)
        echo -n "Starting $DESC: "
        mkdir -p $RUNDIR
        mkdir -p /var/log/stalker
        chown nobody:nogroup $RUNDIR /var/log/stalker
        chmod 755 $RUNDIR
        if start-stop-daemon --start --pidfile $PIDFILE --chuid $USER:$GROUP --exec $DAEMON -- $DAEMON_ARGS_START
        then
                echo "$NAME."
        else
                echo "failed"
        fi
        ;;
  stop)
        echo -n "Stopping $DESC: "
        if start-stop-daemon --stop -s KILL --quiet --pidfile $PIDFILE --name $NAME
        then
                echo "$NAME."
                rm -f $PIDFILE
        else
                echo "failed"
        fi
        ;;

  restart|force-reload)
        ${0} stop
        ${0} start
        ;;

  status)
        echo -n "$DESC is "
        if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
        then
                echo "running"
        else
                echo "not running"
                exit 1
        fi
        ;;

  *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac
exit 0
