#! /bin/sh

### BEGIN INIT INFO
# Provides:          stalkerd
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: stalker
### END INIT INFO

DAEMON_OPTS="-s map"

pid() {
  if [ -f /usr/bin/stalkerd ]; then
    pidof /usr/bin/stalkerd
  fi
}

stop() {
  if pidof /usr/bin/stalkerd >/dev/null; then
    kill "$(pid)"
  else
    echo "stalkerd not running"
    exit 1
  fi
}

start() {
  if pidof /usr/bin/stalkerd >/dev/null; then
    echo "stalkerd already running"
    exit 1
  else
    nohup stalkerd $DAEMON_OPTS > /var/log/stalkerd.log  2>&1 &
  fi
}

restart() {
  if pidof /usr/bin/stalkerd >/dev/null; then
    kill  "$(pid)"
    nohup stalkerd $DAEMON_OPTS > /var/log/stalkerd.log  2>&1 &
    exit 0
  else
    nohup stalkerd $DAEMON_OPTS > /var/log/stalkerd.log  2>&1 &
    exit 0
  fi
}

status() {
  if pidof /usr/bin/stalkerd >/dev/null; then
    echo "stalkerd with pid $(pid) is running"
  else
    echo "stalkerd is not running"
  fi
  exit 0
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  status)
        status
        ;;
  *)
        echo "Usage: service stalkerd {start|stop|restart|status}"
        exit 1
        ;;
esac
